- name: copy interfaces
  copy: src=config/{{ansible_hostname}}/interfaces dest=/etc/network/interfaces.d/vagrant.intf
  
- name: reload networking
  command: ifreload -a -v
  ignore_errors: yes

- name: waiting 5 seconds for network reload
  pause: seconds=5

- name: copy Quagga daemons
  copy: src=config/files/quagga/daemons dest=/etc/quagga/
  
- name: copy Quagga conf
  copy: src=config/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/

- name: reload quagga
  service: name=quagga state=restarted enabled=yes
