#!/bin/sh

# remove old instance if applicable
docker rm  Quagga > /dev/null 2>&1

# start new one
docker run -td --net=host --privileged --name Quagga cumulusnetworks/quagga:xenial-latest

docker cp /etc/quagga/daemons Quagga:/etc/quagga/daemons
docker cp /etc/quagga/Quagga.conf Quagga:/etc/quagga/Quagga.conf

#docker exec Quagga systemctl start quagga.service
docker exec -t Quagga /usr/lib/quagga/quagga start &

exit 0
